// Generated by andromda-angular cartridge (app\usecase\selector.store.ts.vsl) DO NOT EDIT
import { createFeatureSelector, createSelector } from '@ngrx/store';
import { accessPointKey, AccessPointState } from './access-point.state';

export const selectAccessPointState = createFeatureSelector<AccessPointState>(accessPointKey);

export const selectCriteria = createSelector(selectAccessPointState, (state: AccessPointState) => state.criteria);

export const selectAccessPointPage = createSelector(
  selectAccessPointState,
  (state: AccessPointState) => state.accessPointPage
);

export const selectAccessPoint = createSelector(selectAccessPointState, (state: AccessPointState) => state.accessPoint);

export const selectAccessPoints = createSelector(
  selectAccessPointState,
  (state: AccessPointState) => state.accessPoints
);

export const selectId = createSelector(selectAccessPointState, (state: AccessPointState) => state.id);

export const selectLoaderMessage = createSelector(
  selectAccessPointState,
  (state: AccessPointState) => state.loaderMessage
);

export const selectMessages = createSelector(selectAccessPointState, (state: AccessPointState) => state.messages);

export const selectSuccess = createSelector(selectAccessPointState, (state: AccessPointState) => state.success);

export const selectLoading = createSelector(selectAccessPointState, (state: AccessPointState) => state.loading);

export const selectError = createSelector(selectAccessPointState, (state: AccessPointState) => state.error);
