// Generated by andromda-angular cartridge (usecase\use-case.component.ts.vsl) DO NOT EDIT
import { OnInit, Injector, Component, AfterViewInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FarmControllerImpl } from '@app/controller/farm/farm-controller.impl';
import { UseCaseScope } from '@app/utils/use-case-scope';

@Component({
  selector: 'farm',
  template: '',
  standalone: true,
})
export class FarmComponent implements OnInit, AfterViewInit {

    protected route: ActivatedRoute;
    protected router: Router;
    protected _injector: Injector;
    protected useCaseScope: UseCaseScope;
    farmController: FarmControllerImpl;

    constructor(injector: Injector) {
        this.route = injector.get(ActivatedRoute);
        this.router = injector.get(Router);
        this.useCaseScope = injector.get(UseCaseScope);
        this.farmController = injector.get(FarmControllerImpl);
        this._injector = injector;
    }
	
    ngOnInit() {
        
        let forward = this.farmController.startUseCase();
        if(forward !== null) {
            this.router.navigate(['/' + forward]);
        }
    }

    ngAfterViewInit() {
    }

}