// Generated by andromda-angular cartridge (usecase\use-case-routing.module.ts.vsl) DO NOT EDIT
import { importProvidersFrom } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

import { Shell } from '@app/shell/shell.service';
import { FarmComponent } from '@app/view//farm/farm.component';
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { farmFeature } from '@app/store/farm/farm.reducers';
import { FarmEffects } from '@app/store/farm/farm.effects';

import { AuthenticationGuard } from '@app/auth';

import { EditFarmImplComponent } from '@app/view/farm/edit-farm-impl.component';
import { SearchFarmImplComponent } from '@app/view/farm/search-farm-impl.component';
import { FarmViewImplComponent } from '@app/view/farm/farm-view-impl.component';
import { EditPostImplComponent } from '@app/view/farm/edit-post-impl.component';
import { EditCultivationImplComponent } from '@app/view/farm/edit-cultivation-impl.component';
import { EditHarvestImplComponent } from '@app/view/farm/edit-harvest-impl.component';
import { FarmControllerImpl } from '@app/controller/farm/farm-controller.impl';

export const routes: Routes = [
  {
    path: '',
    component: FarmComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Farm') },
    providers: [
      FarmControllerImpl,
      importProvidersFrom(StoreModule.forFeature(farmFeature)),
      importProvidersFrom(EffectsModule.forFeature([FarmEffects])),
    ],
  },
  {
    path: 'edit-farm',
    component: EditFarmImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Edit Farm') },
    providers: [
      // []
      FarmControllerImpl,
      importProvidersFrom(StoreModule.forFeature(farmFeature)),
      importProvidersFrom(EffectsModule.forFeature([FarmEffects])),
    ],
  },
  {
    path: 'search-farm',
    component: SearchFarmImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Search Farm') },
    providers: [
      // []
      FarmControllerImpl,
      importProvidersFrom(StoreModule.forFeature(farmFeature)),
      importProvidersFrom(EffectsModule.forFeature([FarmEffects])),
    ],
  },
  {
    path: 'farm-view',
    component: FarmViewImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Farm View') },
    providers: [
      // []
      FarmControllerImpl,
      importProvidersFrom(StoreModule.forFeature(farmFeature)),
      importProvidersFrom(EffectsModule.forFeature([FarmEffects])),
    ],
  },
  {
    path: 'edit-post',
    component: EditPostImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Edit Post') },
    providers: [
      // []
      FarmControllerImpl,
      importProvidersFrom(StoreModule.forFeature(farmFeature)),
      importProvidersFrom(EffectsModule.forFeature([FarmEffects])),
    ],
  },
  {
    path: 'edit-cultivation',
    component: EditCultivationImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Edit Cultivation') },
    providers: [
      // []
      FarmControllerImpl,
      importProvidersFrom(StoreModule.forFeature(farmFeature)),
      importProvidersFrom(EffectsModule.forFeature([FarmEffects])),
    ],
  },
  {
    path: 'edit-harvest',
    component: EditHarvestImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Edit Harvest') },
    providers: [
      // []
      FarmControllerImpl,
      importProvidersFrom(StoreModule.forFeature(farmFeature)),
      importProvidersFrom(EffectsModule.forFeature([FarmEffects])),
    ],
  },
];
