// Generated by andromda-jsf cartridge (view\table\table.component.spec.ts.vsl)
import { waitForAsync, ComponentFixture, TestBed } from '@angular/core/testing';

import { SearchFarmFarmsImplComponent } from '@app/view/farm/search-farm-farms-impl.component';

describe('SearchFarmFarmsImplComponent', () => {
  let component: SearchFarmFarmsImplComponent;
  let fixture: ComponentFixture<SearchFarmFarmsImplComponent>;

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      declarations: [SearchFarmFarmsImplComponent],
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(SearchFarmFarmsImplComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
