// Generated by andromda-jsf cartridge (view\table\table-impl.component.ts.vsl)
import { Component } from '@angular/core';
import { SearchFarmFarmsComponent } from '@app/view/farm/search-farm-farms.component';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';

@Component({
  selector: 'app-search-farm-farms',
  templateUrl: './search-farm-farms.component.html',
  styleUrls: [ './search-farm-farms.component.scss' ],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
  ],
})
export class SearchFarmFarmsImplComponent extends SearchFarmFarmsComponent {

  constructor() {
    super();
  }


	override doSearchFarmEdit(form: any): any {
    return form;
	}

	override doSearchFarmDetails(form: any): any {
    return form;
	}
}