// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable, Injector } from '@angular/core';
import { AccessPointController } from '@app/controller/access/access-point-controller';

@Injectable()
export class AccessPointControllerImpl extends AccessPointController {
  constructor(private injector: Injector) {
    super(injector);
  }

  public doInitialiseEditScreen(form: any): void {}

  public doDelete(form: any): void {}

  public doSave(form: any): void {}

  public doInitialiseSearchScreen(form: any): void {}

  public doSearch(form: any): void {}

  public doEdit(form: any): void {}
}
