// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.sigmaproduce::TimePeriod
 */
export enum TimePeriod {
    /** TODO: Model Documentation for Enumeration Literal WEEK value "WEEK" */
    WEEK = "WEEK",
    /** TODO: Model Documentation for Enumeration Literal MONTH value "MONTH" */
    MONTH = "MONTH",
    /** TODO: Model Documentation for Enumeration Literal YEAR value "YEAR" */
    YEAR = "YEAR"
}
