// Generated by andromda-angular cartridge (app\usecase\effect.store.ts.vsl) DO NOT EDIT
import { Injectable } from '@angular/core';
import { Actions, createEffect, ofType } from '@ngrx/effects';

@Injectable()
export class AuthEffects {
  constructor(private actions$: Actions) {}

  // isLoggedIn$ = createEffect(() =>
  //   this.actions$.pipe(
  //     ofType(AuthActions.isLoggedIn),
  //     mergeMap(() =>
  //       this.keycloakService.isLoggedIn().then(
  //         map((isLoggedIn) => {

  //           if(isLoggedIn) {
  //             AuthActions.getMenus();
  //             AuthActions.getRolesSuccess({roles: this.keycloakService.getUserRoles()});
  //           }
  //         }),
  //         catchmessage(({ messages }) => [AuthActions.authFailure(messages)])
  //       )
  //     )
  //   )
  // );

  // logout$ = createEffect(() =>
  //   this.actions$.pipe(
  //     ofType(AuthActions.logout),
  //     mergeMap(() =>
  //       this.keycloakService.logout().then(
  //         map(() => AuthActions.authReset()),
  //         catchmessage(({ messages }) => [AuthActions.authFailure(messages)])
  //       )
  //     )
  //   )
  // );
}
