// Generated by andromda-angular cartridge (app\usecase\selector.store.ts.vsl) DO NOT EDIT
import { createFeatureSelector, createSelector } from '@ngrx/store';
import { accessPointTypeKey, AccessPointTypeState } from './access-point-type.state';

export const selectAccessPointTypeState = createFeatureSelector<AccessPointTypeState>(accessPointTypeKey);

export const selectAccessPointTypes = createSelector(
  selectAccessPointTypeState,
  (state: AccessPointTypeState) => state.accessPointTypes
);

export const selectAccessPointType = createSelector(
  selectAccessPointTypeState,
  (state: AccessPointTypeState) => state.accessPointType
);

export const selectCriteria = createSelector(
  selectAccessPointTypeState,
  (state: AccessPointTypeState) => state.criteria
);

export const selectId = createSelector(selectAccessPointTypeState, (state: AccessPointTypeState) => state.id);

export const selectLoaderMessage = createSelector(
  selectAccessPointTypeState,
  (state: AccessPointTypeState) => state.loaderMessage
);

export const selectMessages = createSelector(
  selectAccessPointTypeState,
  (state: AccessPointTypeState) => state.messages
);

export const selectSuccess = createSelector(selectAccessPointTypeState, (state: AccessPointTypeState) => state.success);

export const selectLoading = createSelector(selectAccessPointTypeState, (state: AccessPointTypeState) => state.loading);

export const selectError = createSelector(selectAccessPointTypeState, (state: AccessPointTypeState) => state.error);
