// Generated by andromda-angular cartridge (usecase\use-case.component.ts.vsl) DO NOT EDIT
import { OnInit, Injector, Component, AfterViewInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CropTypeControllerImpl } from '@app/controller/crop/type/crop-type-controller.impl';
import { UseCaseScope } from '@app/utils/use-case-scope';

@Component({
  selector: 'crop-types',
  template: '',
  standalone: true,
})
export class CropTypesComponent implements OnInit, AfterViewInit {
  protected route: ActivatedRoute;
  protected router: Router;
  protected _injector: Injector;
  protected useCaseScope: UseCaseScope;
  cropTypeController: CropTypeControllerImpl;

  constructor(injector: Injector) {
    this.route = injector.get(ActivatedRoute);
    this.router = injector.get(Router);
    this.useCaseScope = injector.get(UseCaseScope);
    this.cropTypeController = injector.get(CropTypeControllerImpl);
    this._injector = injector;
  }

  ngOnInit() {
    let forward = this.cropTypeController.startUseCase();
    if (forward !== null) {
      this.router.navigate(['/' + forward]);
    }
  }

  ngAfterViewInit() {}
}
