// Generated by andromda-angular cartridge (usecase\use-case-routing.module.ts.vsl) DO NOT EDIT
import { importProvidersFrom } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

import { Shell } from '@app/shell/shell.service';
import { CropTypesComponent } from '@app/view//crop/type/crop-types.component';
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { cropTypeFeature } from '@app/store/crop/type/crop-type.reducers';
import { CropTypeEffects } from '@app/store/crop/type/crop-type.effects';

import { AuthenticationGuard } from '@app/auth';

import { EditCropTypeImplComponent } from '@app/view/crop/type/edit-crop-type-impl.component';
import { SearchCropTypesImplComponent } from '@app/view/crop/type/search-crop-types-impl.component';
import { CropTypeViewImplComponent } from '@app/view/crop/type/crop-type-view-impl.component';
import { CropTypeControllerImpl } from '@app/controller/crop/type/crop-type-controller.impl';

export const routes: Routes = [
  {
    path: '',
    component: CropTypesComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Crop Types') },
    providers: [
      CropTypeControllerImpl,
      importProvidersFrom(StoreModule.forFeature(cropTypeFeature)),
      importProvidersFrom(EffectsModule.forFeature([CropTypeEffects])),
    ],
  },
  {
    path: 'edit-crop-type',
    component: EditCropTypeImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Edit Crop Type') },
    providers: [
      // []
      CropTypeControllerImpl,
      importProvidersFrom(StoreModule.forFeature(cropTypeFeature)),
      importProvidersFrom(EffectsModule.forFeature([CropTypeEffects])),
    ],
  },
  {
    path: 'search-crop-types',
    component: SearchCropTypesImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Search Crop Types') },
    providers: [
      // []
      CropTypeControllerImpl,
      importProvidersFrom(StoreModule.forFeature(cropTypeFeature)),
      importProvidersFrom(EffectsModule.forFeature([CropTypeEffects])),
    ],
  },
  {
    path: 'crop-type-view',
    component: CropTypeViewImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Crop Type View') },
    providers: [
      // []
      CropTypeControllerImpl,
      importProvidersFrom(StoreModule.forFeature(cropTypeFeature)),
      importProvidersFrom(EffectsModule.forFeature([CropTypeEffects])),
    ],
  },
];
