// Generated by andromda-angular cartridge (view\view.component.ts.vsl) DO NOT EDIT
import { 
    Component, 
    OnInit, 
    inject, 
    ViewChild, 
    Input, 
    Output, 
    EventEmitter, 
    AfterViewInit,
    signal,
    OnDestroy,
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { 
    FormGroup, 
    FormControl, 
    FormArray, 
    FormBuilder, 
    ReactiveFormsModule, 
    Validators 
} from '@angular/forms';
import { formatDate } from '@angular/common';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatSelectChange } from '@angular/material/select';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { UseCaseScope } from '@app/utils/use-case-scope';
import { SelectItem } from '@app/utils/select-item';
import { Store, select } from '@ngrx/store';
import { Observable, Subscription } from 'rxjs';
import { MatDialog } from '@angular/material/dialog';
import { MatTableDataSource } from '@angular/material/table';
import { CropTypeState } from '@app/store/crop/type/crop-type.state';
import * as CropTypeSelectors from '@app/store/crop/type/crop-type.selectors';
import * as CropTypeActions from '@app/store/crop/type/crop-type.actions';

import { CropTypeDetailsComponent } from '@app/components/crop/type/crop-type-details.component';
import { CropTypeControllerImpl } from '@app/controller/crop/type/crop-type-controller.impl';
import { CropTypeEditorComponent } from '@app/components/crop/type/crop-type-editor.component';
import { CropTypeVO } from '@app/model/bw/co/sigmaproduce/crop/type/crop-type-vo';

export class CropTypeViewVarsForm {
    cropTypeDetails: CropTypeDetailsComponent | any;
}

@Component({
  selector: 'app-crop-type-view-base',
  template: ''
})
export abstract class CropTypeViewComponent implements OnInit, AfterViewInit, OnDestroy {

	cropTypeViewForm: FormGroup = new FormGroup({});
    hide: boolean = false;
    protected route: ActivatedRoute = inject(ActivatedRoute);
    protected router: Router = inject(Router);
    protected formBuilder: FormBuilder = inject(FormBuilder);
    protected useCaseScope: UseCaseScope = inject(UseCaseScope);
    protected store: Store<CropTypeState> = inject(Store);
    dialog: MatDialog = inject(MatDialog);
    cropTypeController: CropTypeControllerImpl = inject(CropTypeControllerImpl);
    @ViewChild('cropTypeDetails') cropTypeDetailsComponent?: CropTypeDetailsComponent;
    cropTypeDetailsForm: FormGroup = new FormGroup({});
    messages: Observable<any>;
    messagesSubscription?: Subscription;
    success: Observable<boolean>;
    successSubscription?: Subscription;
    loading: Observable<boolean>;
    loadingSubscription?: Subscription;
    error: Observable<boolean>;
    errorSubscription?: Subscription;
    selected: any = null;

    cropTypeViewFormValueSubscription?: Subscription;

    constructor() {
        this.loading = this.store.pipe(select(CropTypeSelectors.selectLoading));
        this.success = this.store.pipe(select(CropTypeSelectors.selectSuccess));
        this.error = this.store.pipe(select(CropTypeSelectors.selectError));
        this.messages = this.store.pipe(select(CropTypeSelectors.selectMessages));
    }

    abstract beforeOnInit(form: CropTypeViewVarsForm): CropTypeViewVarsForm;
	
    ngOnInit() {
        let form: CropTypeViewVarsForm = this.beforeOnInit(new CropTypeViewVarsForm);
        this.cropTypeViewForm = this.newForm(form);

        this.cropTypeViewFormValueSubscription = this.cropTypeViewForm.valueChanges.subscribe(
            (change: any) => {
                this.handleFormChanges(change);
            }
        );
        
        this.afterOnInit();
        this.cropTypeDetailsForm = this.cropTypeDetailsControl;
    }

    handleFormChanges(change: any): void {
        
    }

    cropTypeViewFormReset() {

        this.store.dispatch(CropTypeActions.cropTypeReset());
        this.cropTypeViewForm.reset()
        this.cropTypeViewForm.markAsPristine();

        if(this.router.url.substring(0, this.router.url.indexOf('?'))) {
            this.router.navigate([this.router.url.substring(0, this.router.url.indexOf('?'))]);
        } else {
            this.router.navigate([this.router.url]);
        }
    }

    afterOnInit(): void {}
    
    doNgAfterViewInit(): void {}

    ngAfterViewInit() {
        this.doNgAfterViewInit();
        this.cropTypeController.resetUseCaseScope();
    }

    newForm(cropTypeViewVarsForm$: CropTypeViewVarsForm): FormGroup {
        return this.formBuilder.group({
            cropTypeDetails: this.createCropTypeDetailsForm(cropTypeViewVarsForm$?.cropTypeDetails),
        });
    }

    abstract doNgOnDestroy(): void;

    ngOnDestroy() { 
        this.doNgOnDestroy();

        if(this.cropTypeViewFormValueSubscription) {
            this.cropTypeViewFormValueSubscription.unsubscribe();
        }
        
        this.store.dispatch(CropTypeActions.cropTypeReset());
        if(this.messagesSubscription) {
            this.messagesSubscription.unsubscribe();
        }

        if(this.successSubscription) {
            this.successSubscription.unsubscribe();
        }

        if(this.loadingSubscription) {
            this.loadingSubscription.unsubscribe();
        }

        if(this.errorSubscription) {
            this.errorSubscription.unsubscribe();
        }
    }


    /**
     * This method may be overwritten
     */
    beforeCropTypeViewEdit(form: any): void {}

    /**
     * This method may be overwritten
     */
    afterCropTypeViewEdit(form: any): void {}

    /**
     * This method may be overwritten
     */
    get cropTypeViewEditId(): string {
        return {} as string;
    }

    cropTypeViewEdit(): void {

        let form: any = {
            id: this.cropTypeViewEditId,
        };

        this.beforeCropTypeViewEdit(form);

        this.cropTypeController.cropTypeViewEdit(form);
        this.afterCropTypeViewEdit(form);
    }

    get cropTypeViewVarsFormControl(): FormGroup {
        return this.getGroupControl('cropTypeViewVarsForm');
    }

    createCropTypeDetailsForm(cropTypeDetails?: CropTypeDetailsComponent): FormGroup {
        return this.formBuilder.group({
            id: [{value: cropTypeDetails?.id, disabled: false}],
            createdBy: [{value: cropTypeDetails?.createdBy, disabled: false}],
            updatedBy: [{value: cropTypeDetails?.updatedBy, disabled: false}],
            createdDate: [{value: cropTypeDetails?.createdDate, disabled: false}],
            updatedDate: [{value: cropTypeDetails?.updatedDate, disabled: false}],
            code: [{value: cropTypeDetails?.code, disabled: false}, [Validators.required, ]],
            name: [{value: cropTypeDetails?.name, disabled: false}, [Validators.required, ]],
            images: this.formBuilder.array(cropTypeDetails?.images ? cropTypeDetails.images : []),
            description: [{value: cropTypeDetails?.description, disabled: false}],
            numberOfCrops: [{value: cropTypeDetails?.numberOfCrops, disabled: false}],
            numberOfDiseases: [{value: cropTypeDetails?.numberOfDiseases, disabled: false}],
            numberOfPests: [{value: cropTypeDetails?.numberOfPests, disabled: false}],
        });
    }

    get cropTypeDetailsControl(): FormGroup {
        return this.getGroupControl('cropTypeDetails') as FormGroup;
    }

    get cropTypeDetails(): CropTypeDetailsComponent {
        return this.cropTypeDetailsControl.value;
    }

    get cropTypeDetailsIdControl(): FormControl {
        return this.cropTypeDetailsControl.get('id') as FormControl;
    }

    get cropTypeDetailsId(): string {
        return this.cropTypeDetailsIdControl.value;
    }

    get cropTypeDetailsCreatedByControl(): FormControl {
        return this.cropTypeDetailsControl.get('createdBy') as FormControl;
    }

    get cropTypeDetailsCreatedBy(): string {
        return this.cropTypeDetailsCreatedByControl.value;
    }

    get cropTypeDetailsUpdatedByControl(): FormControl {
        return this.cropTypeDetailsControl.get('updatedBy') as FormControl;
    }

    get cropTypeDetailsUpdatedBy(): string {
        return this.cropTypeDetailsUpdatedByControl.value;
    }

    get cropTypeDetailsCreatedDateControl(): FormControl {
        return this.cropTypeDetailsControl.get('createdDate') as FormControl;
    }

    get cropTypeDetailsCreatedDate(): Date {
        return this.cropTypeDetailsCreatedDateControl.value;
    }

    get cropTypeDetailsUpdatedDateControl(): FormControl {
        return this.cropTypeDetailsControl.get('updatedDate') as FormControl;
    }

    get cropTypeDetailsUpdatedDate(): Date {
        return this.cropTypeDetailsUpdatedDateControl.value;
    }

    get cropTypeDetailsCodeControl(): FormControl {
        return this.cropTypeDetailsControl.get('code') as FormControl;
    }

    get cropTypeDetailsCode(): string {
        return this.cropTypeDetailsCodeControl.value;
    }

    get cropTypeDetailsNameControl(): FormControl {
        return this.cropTypeDetailsControl.get('name') as FormControl;
    }

    get cropTypeDetailsName(): string {
        return this.cropTypeDetailsNameControl.value;
    }

    get cropTypeDetailsImagesControl(): FormArray {
        return this.cropTypeDetailsControl.get('images') as FormArray;
    }

    get cropTypeDetailsImages(): File[] {
        return this.cropTypeDetailsImagesControl.value;
    }

    get cropTypeDetailsDescriptionControl(): FormControl {
        return this.cropTypeDetailsControl.get('description') as FormControl;
    }

    get cropTypeDetailsDescription(): string {
        return this.cropTypeDetailsDescriptionControl.value;
    }

    get cropTypeDetailsNumberOfCropsControl(): FormControl {
        return this.cropTypeDetailsControl.get('numberOfCrops') as FormControl;
    }

    get cropTypeDetailsNumberOfCrops(): number {
        return this.cropTypeDetailsNumberOfCropsControl.value;
    }

    get cropTypeDetailsNumberOfDiseasesControl(): FormControl {
        return this.cropTypeDetailsControl.get('numberOfDiseases') as FormControl;
    }

    get cropTypeDetailsNumberOfDiseases(): number {
        return this.cropTypeDetailsNumberOfDiseasesControl.value;
    }

    get cropTypeDetailsNumberOfPestsControl(): FormControl {
        return this.cropTypeDetailsControl.get('numberOfPests') as FormControl;
    }

    get cropTypeDetailsNumberOfPests(): number {
        return this.cropTypeDetailsNumberOfPestsControl.value;
    }

    getItemControl(name: string): FormControl {
        return this.cropTypeViewForm.get(name) as FormControl;
    }

    getGroupControl(name: string): FormGroup {
        return this.cropTypeViewForm.get(name) as FormGroup;
    }

    getArrayControl(name: string): FormArray {
        return this.cropTypeViewForm.get(name) as FormArray;
    }

    setCropTypeViewFormValue(form: any) {
        if(form.cropTypeDetails) {
            this.cropTypeViewForm.setControl('cropTypeDetails', this.createCropTypeDetailsForm(form.cropTypeDetails));
        }
    }

    createCropTypeDetailsComponentGroup(value?: CropTypeDetailsComponent): FormGroup { 
        return this.formBuilder.group({
            id: [value?.id],
            createdBy: [value?.createdBy],
            updatedBy: [value?.updatedBy],
            createdDate: [value?.createdDate],
            updatedDate: [value?.updatedDate],
            code: [value?.code],
            name: [value?.name],
            description: [value?.description],
            numberOfCrops: [value?.numberOfCrops],
            numberOfDiseases: [value?.numberOfDiseases],
            numberOfPests: [value?.numberOfPests],
        });
    }

    createCropTypeDetailsComponentArray(values?: CropTypeDetailsComponent[]): FormArray {
        if(values) {
            let formArray: FormArray = this.formBuilder.array([]);
            values?.forEach(value => formArray.push(this.createCropTypeDetailsComponentGroup(value)))

            return formArray;
        } else {
            return new FormArray([] as any);
        }
    }

    createCropTypeEditorComponentGroup(value?: CropTypeEditorComponent): FormGroup { 
        return this.formBuilder.group({
            id: [value?.id],
            createdBy: [value?.createdBy],
            updatedBy: [value?.updatedBy],
            createdDate: [value?.createdDate],
            updatedDate: [value?.updatedDate],
            code: [value?.code],
            name: [value?.name],
            description: [value?.description],
        });
    }

    createCropTypeEditorComponentArray(values?: CropTypeEditorComponent[]): FormArray {
        if(values) {
            let formArray: FormArray = this.formBuilder.array([]);
            values?.forEach(value => formArray.push(this.createCropTypeEditorComponentGroup(value)))

            return formArray;
        } else {
            return new FormArray([] as any);
        }
    }

    createCropTypeVOGroup(value?: CropTypeVO): FormGroup { 
        return this.formBuilder.group({
            createdBy: [value?.createdBy],
            updatedBy: [value?.updatedBy],
            createdDate: [value?.createdDate],
            updatedDate: [value?.updatedDate],
            description: [value?.description],
            numberOfCrops: [value?.numberOfCrops],
            numberOfDiseases: [value?.numberOfDiseases],
            numberOfPests: [value?.numberOfPests],
        });
    }

    createCropTypeVOArray(values?: CropTypeVO[]): FormArray {
        if(values) {
            let formArray: FormArray = this.formBuilder.array([]);
            values?.forEach(value => formArray.push(this.createCropTypeVOGroup(value)))

            return formArray;
        } else {
            return new FormArray([] as any);
        }
    }

}
