// Generated by andromda-angular cartridge (view\view.component.spec.ts.vsl) DO NOT EDIT!
import { waitForAsync, ComponentFixture, TestBed } from '@angular/core/testing';
import { EditCropTypeImplComponent } from '@app/view/crop/type/edit-crop-type-impl.component.';

describe('EditCropTypeImplComponent', () => {
	let component: EditCropTypeImplComponent;
	let fixture: ComponentFixture<EditCropTypeImplComponent>;

	beforeEach(waitForAsync(() => {
		TestBed.configureTestingModule({
			declarations: [EditCropTypeImplComponent]
		})
			.compileComponents();
	}));

	beforeEach(() => {
		fixture = TestBed.createComponent(EditCropTypeImplComponent);
		component = fixture.componentInstance;
		fixture.detectChanges();
	});

	it('should create', () => {
		expect(component).toBeTruthy();
	});
});
