// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.sigmaproduce::farm::cultivation::harvest::HarvestUnit
 */
export enum HarvestUnit {
    /** TODO: Model Documentation for Enumeration Literal KILOGRAMS value "KILOGRAMS" */
    KILOGRAMS = "KILOGRAMS",
    /** TODO: Model Documentation for Enumeration Literal TONNES value "TONNES" */
    TONNES = "TONNES",
    /** TODO: Model Documentation for Enumeration Literal UNITS value "UNITS" */
    UNITS = "UNITS",
    /** TODO: Model Documentation for Enumeration Literal BAGS value "BAGS" */
    BAGS = "BAGS",
    /** TODO: Model Documentation for Enumeration Literal BUNDLES value "BUNDLES" */
    BUNDLES = "BUNDLES"
}
