// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { DistrictVO } from '@app/model/district/district-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';

@Injectable({
  providedIn: 'root',
})
export class DistrictApi {
  protected path = '/district';

  constructor(private http: HttpClient) {}

  public findById(id: number | any): Observable<DistrictVO | any> {
    return this.http.get<DistrictVO | any>(this.path + `/${id}`);
  }

  public getAll(): Observable<DistrictVO[] | any[]> {
    return this.http.get<DistrictVO[] | any[]>(this.path);
  }

  public remove(id: number | any): Observable<boolean | any> {
    return this.http.delete<boolean | any>(this.path + `/${id}`);
  }

  public save(district: DistrictVO | any): Observable<DistrictVO | any> {
    return this.http.post<DistrictVO | any>(this.path, district);
  }

  public search(criteria: string | any): Observable<DistrictVO[] | any[]> {
    return this.http.get<DistrictVO[] | any[]>(this.path + `/search`);
  }
}
