// Generated by andromda-angular cartridge (app\usecase\reducer.store.ts.vsl) DO NOT EDIT
import { Action, createFeature, createReducer, on } from '@ngrx/store';
import * as FarmActions from './farm.actions';
import {farmKey, initialState} from './farm.state';

export const farmReducer = createReducer(
    initialState,
    on(FarmActions.farmReset, (state) => ({
      ...state,
        criteria: null, 
        farms: [], 
        id: null, 
        cultivation: null, 
        loading: false,
        success: false,
        error: false,
        messges: []
    })),
    on(FarmActions.farmFailure, (state, action) => ({
        ...state,
        loading: false,
        success: false,
        error: true,
        messages: action.messages
    })),
    on(FarmActions.farmLoading, (state, action) => ({
        ...state,
        loading: action.loading,
        success: false
    }))
);

export const farmFeature = createFeature({
    name: farmKey,
    reducer: farmReducer
});
