// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector, ViewChild } from '@angular/core';
import { SearchAccessPointsComponent } from '@app/view/access/search-access-points.component';
import { SearchAccessPointsSearchForm } from '@app/view/access/search-access-points.component';
import { SearchAccessPointsVarsForm } from '@app/view/access/search-access-points.component';
import * as AccessPointActions from '@app/store/access/access-point.actions';

@Component({
  selector: 'app-search-access-points',
  templateUrl: './search-access-points.component.html',
  styleUrls: ['./search-access-points.component.scss'],
})
export class SearchAccessPointsComponentImpl extends SearchAccessPointsComponent {
  constructor(private injector: Injector) {
    super(injector);
  }

  override beforeOnInit(form: SearchAccessPointsVarsForm): SearchAccessPointsVarsForm {
    return form;
  }

  override doNgOnDestroy() {}

  /**
   * This method may be overwritten
   */
  override beforeSearchAccessPointsSearch(form: SearchAccessPointsSearchForm): void {
    this.searchAccessPointsAccessPointsComponent.criteria = form.criteria;
    this.searchAccessPointsAccessPointsComponent.accessPointsPaginator.pageIndex = 0;

    this.store.dispatch(
      AccessPointActions.pagedSearch({
        pageNumber: this.searchAccessPointsAccessPointsComponent.accessPointsPaginator.pageIndex + 1,
        pageSize: this.searchAccessPointsAccessPointsComponent.accessPointsPaginator.pageSize,
        criteria: form.criteria,
        loading: true,
        loaderMessage: 'Searching access points ...',
      })
    );
  }
}
