// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { CropController } from '@app/controller/crop/crop-controller';

@Injectable()
export class CropControllerImpl extends CropController {
  constructor() {
    super();
  }
}
