// Generated by andromda-angular cartridge (usecase\use-case-routing.module.ts.vsl) DO NOT EDIT
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

import { Shell } from '@app/shell/shell.service';
// import { AccessPointType } from '@app/view//access/type/access-point-type.component';

import { AuthenticationGuard } from '@app/auth';

import { EditAccessPointTypeComponentImpl } from '@app/view/access/type/edit-access-point-type.component.impl';
import { SearchAccessPointTypesComponentImpl } from '@app/view/access/type/search-access-point-types.component.impl';

const routes: Routes = [
  {
    path: '',
    component: EditAccessPointTypeComponentImpl,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Access Point Type') },
  },
  {
    path: 'edit-access-point-type',
    component: EditAccessPointTypeComponentImpl,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Edit Access Point Type') },
  },
  {
    path: 'search-access-point-types',
    component: SearchAccessPointTypesComponentImpl,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Search Access Point Types') },
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: [],
})
export class AccessPointTypeRoutingModule {}
