// Generated by andromda-angular cartridge (view\use-case.module.ts.vsl) DO NOT EDIT
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { SharedModule } from '@shared';
import { CsvModule } from '@ctrl/ngx-csv';
import { MaterialModule } from '@app/material.module';
import { MatTableExporterModule } from 'mat-table-exporter';
import { AccessPointTypeRoutingModule } from './access-point-type-routing.module';
import { EditAccessPointTypeComponentImpl } from '@app/view/access/type/edit-access-point-type.component.impl'; // 1
import { SearchAccessPointTypesComponentImpl } from '@app/view/access/type/search-access-point-types.component.impl'; // 1
import { SearchAccessPointTypesAccessPointTypesComponentImpl } from '@app/view/access/type/search-access-point-types-access-point-types.component.impl'; // 2
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { accessPointTypeFeature } from '@app/store/access/type/access-point-type.reducers';
import { AccessPointTypeEffects } from '@app/store/access/type/access-point-type.effects';
import { AccessPointTypeControllerImpl } from '@app/controller/access/type/access-point-type-controller.impl';
import { AccessPointTypeRestController } from '@app/service//access/type/access-point-type-rest-controller';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    FlexLayoutModule,
    MaterialModule,
    CsvModule,
    MatTableExporterModule,
    AccessPointTypeRoutingModule,
    SharedModule,
    StoreModule.forFeature(accessPointTypeFeature),
    EffectsModule.forFeature([AccessPointTypeEffects]),
  ],
  declarations: [
    EditAccessPointTypeComponentImpl,
    SearchAccessPointTypesComponentImpl,
    SearchAccessPointTypesAccessPointTypesComponentImpl,
  ],
  entryComponents: [],
  providers: [AccessPointTypeControllerImpl, AccessPointTypeRestController],
})
export class AccessPointTypeModule {}
