// Generated by andromda-angular cartridge (view\view.component.spec.ts.vsl) DO NOT EDIT!
import { waitForAsync, ComponentFixture, TestBed } from '@angular/core/testing';
import { EditAccessPointTypeComponentImpl } from '@app/view/access/type/edit-access-point-type.component.impl.';

describe('EditAccessPointTypeComponentImpl', () => {
  let component: EditAccessPointTypeComponentImpl;
  let fixture: ComponentFixture<EditAccessPointTypeComponentImpl>;

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      declarations: [EditAccessPointTypeComponentImpl],
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(EditAccessPointTypeComponentImpl);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
