// Generated by andromda-angular cartridge (app\usecase\state.store.ts.vsl) DO NOT EDIT
import { CropTypeListVO } from '@app/model/bw/co/sigmaproduce/crop/type/crop-type-list-vo';
import { CropTypeVO } from '@app/model/bw/co/sigmaproduce/crop/type/crop-type-vo';

export const cropTypeKey = "cropType";

export interface CropTypeState {
    criteria: String | any;
    cropType: CropTypeVO | any;
    id: String | any;
    cropTypes: Array<CropTypeListVO> | any[];
    loading: boolean;
    success: boolean;
    error: boolean;
    messages: string[];
}

export const initialState: CropTypeState = {
    criteria: null,
    cropType: null,
    id: null,
    cropTypes: [],
    loading: false,
    success: false,
    error: false,
    messages: []
};