// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { FarmController } from '@app/controller/farm/farm-controller';

@Injectable()
export class FarmControllerImpl extends FarmController {

    constructor() {
        super();
    }

}
