// Generated by andromda-angular cartridge (app\usecase\state.store.ts.vsl) DO NOT EDIT

export const viewKey = 'view';

export interface ViewState {
  viewName: string;
  unauthorisedUrls: string[];
  loading: boolean;
  success: boolean;
  error: boolean;
  messages: string[];
}

export const initialState: ViewState = {
  loading: false,
  success: false,
  error: false,
  messages: [],
  unauthorisedUrls: [],
  viewName: '',
};
