// Generated by andromda-angular cartridge (app\usecase\reducer.store.ts.vsl) DO NOT EDIT
import { Action, createFeature, createReducer, on } from '@ngrx/store';
import * as ViewActions from './view.actions';
import { viewKey, initialState } from './view.state';

export const viewReducer = createReducer(
  initialState,

  on(ViewActions.loadViewAuthorisationsSuccess, (state, action) => ({
    ...state,
    viewName: '',
    unauthorisedUrls: action.unauthorisedUrls,
    loading: false,
    success: action.success,
    error: false,
    messges: [],
  })),
  on(ViewActions.viewReset, (state) => ({
    ...state,
    viewName: '',
    unauthorisedUrls: [],
    loading: false,
    success: false,
    error: false,
    messges: [],
  })),
  on(ViewActions.viewFailure, (state, action) => ({
    ...state,
    loading: false,
    success: false,
    error: true,
    messages: action.messages,
  })),
  on(ViewActions.viewLoading, (state, action) => ({
    ...state,
    loading: action.loading,
    success: false,
  }))
);

export const viewFeature = createFeature({
  name: viewKey,
  reducer: viewReducer,
});
