// Generated by andromda-angular cartridge (app\usecase\action.store.ts.vsl) DO NOT EDIT
import { createAction, props } from '@ngrx/store';

export enum ViewActionType {
  SET_VIEW_NAME = '[View] Set View Name',
  LOAD_VIEW_AUTHORISATIONS = '[View] Load View Authorisations',
  LOAD_VIEW_AUTHORISATIONS_SUCCESS = '[View] Load View Authorisations Success',
  VIEW_RESET = '[View] View Reset',
  VIEW_FAILURE = '[View] View Action Failure',
  VIEW_LOADING = '[View] View Loading',
}

export const setViewName = createAction(ViewActionType.SET_VIEW_NAME, props<{ viewName: string }>());

export const loadViewAuthorisations = createAction(
  ViewActionType.LOAD_VIEW_AUTHORISATIONS,
  props<{ viewUrl: string; roles: string[]; loading: boolean }>()
);

export const loadViewAuthorisationsSuccess = createAction(
  ViewActionType.LOAD_VIEW_AUTHORISATIONS_SUCCESS,
  props<{ unauthorisedUrls: string[]; success: boolean }>()
);

export const viewReset = createAction(ViewActionType.VIEW_RESET);

export const viewLoading = createAction(
  ViewActionType.VIEW_LOADING,
  props<{ loading: boolean; success: boolean; messages: any[] }>()
);

export const viewFailure = createAction(ViewActionType.VIEW_FAILURE, props<{ messages: any[] }>());
