// Generated by andromda-angular cartridge (usecase\use-case.component.ts.vsl) DO NOT EDIT
import { OnInit, Injector, Component, AfterViewInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthorisationControllerImpl } from '@app/controller/auth/authorisation-controller.impl';
import { UseCaseScope } from '@app/utils/use-case-scope';

@Component({
  selector: 'app-authorisations',
  template: '',
})
export class AuthorisationsComponent implements OnInit, AfterViewInit {
  protected route: ActivatedRoute;
  protected router: Router;
  protected _injector: Injector;
  protected useCaseScope: UseCaseScope;
  authorisationController: AuthorisationControllerImpl;

  constructor(injector: Injector) {
    this.route = injector.get(ActivatedRoute);
    this.router = injector.get(Router);
    this.useCaseScope = injector.get(UseCaseScope);
    this.authorisationController = injector.get(AuthorisationControllerImpl);
    this._injector = injector;
  }

  ngOnInit() {
    let forward = this.authorisationController.startUseCase();
    if (forward !== null) {
      this.router.navigate(['/' + forward]);
    }
  }

  ngAfterViewInit() {}
}
