// Generated by andromda-jsf cartridge (view\table\table.component.spec.ts.vsl)
import { waitForAsync, ComponentFixture, TestBed } from '@angular/core/testing';

import { SearchAuthorisationsAuthorisationsComponentImpl } from '@app/view/auth/search-authorisations-authorisations.component.impl';

describe('SearchAuthorisationsAuthorisationsComponentImpl', () => {
  let component: SearchAuthorisationsAuthorisationsComponentImpl;
  let fixture: ComponentFixture<SearchAuthorisationsAuthorisationsComponentImpl>;

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      declarations: [SearchAuthorisationsAuthorisationsComponentImpl],
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(SearchAuthorisationsAuthorisationsComponentImpl);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
