// Generated by andromda-angular cartridge (view\components\component.ts.vsl) DO NOT EDIT
import {
  AfterViewInit,
  Component,
  Input,
  OnDestroy,
  OnInit,
  ViewChild,
} from "@angular/core";
import {COMMA, ENTER} from '@angular/cdk/keycodes';
import {
  FormsModule,
  ReactiveFormsModule,
  FormGroup,
  FormControl,
  FormBuilder,
  Validators,
  FormArray,
} from "@angular/forms";
import { SelectItem } from "@app/utils/select-item";
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatSelectChange } from '@angular/material/select';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { MatChip, MatChipInput, MatChipInputEvent } from "@angular/material/chips";
import {MatAutocompleteSelectedEvent, MatAutocompleteModule} from '@angular/material/autocomplete';
import { MatDialog } from '@angular/material/dialog';
import { Observable, map, of, startWith } from "rxjs";
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';

@Component({
  selector: "app-post-editor",
  templateUrl: "./post-editor.component.html",
  styleUrls: [],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
  ]
})
export class PostEditorComponent implements OnInit, OnDestroy, AfterViewInit {

    separatorKeysCodes: number[] = [ENTER, COMMA];
    @Input() postEditorForm: FormGroup = new FormGroup({});

    @Input() id?: string;

    @Input() createdBy?: string;

    @Input() updatedBy?: string;

    @Input() createdDate?: Date;

    @Input() updatedDate?: Date;

    @Input() content?: string;

    @Input() images?: File[];

    imagesPreviews: any[] = [];
    imagesSelectedFiles?: FileList;

    constructor(
      private formBuilder: FormBuilder
    ) {
    }

    ngOnInit() {
        if(!this.postEditorForm) {
            this.initForm();
        }
    }

    ngOnDestroy() {}

    ngAfterViewInit() {

    }

    initForm() {
        this.postEditorForm = this.formBuilder.group({
            id: [{value: this.id, disabled: false}],
            createdBy: [{value: this.createdBy, disabled: false}],
            updatedBy: [{value: this.updatedBy, disabled: false}],
            createdDate: [{value: this.createdDate, disabled: false}],
            updatedDate: [{value: this.updatedDate, disabled: false}],
            content: [{value: this.content, disabled: false}],
            images: this.formBuilder.array(this.images ? this.images : []),
        });
    }


    get idControl(): FormControl {
        return this.postEditorForm?.get('id') as FormControl;
    }


    get createdByControl(): FormControl {
        return this.postEditorForm?.get('createdBy') as FormControl;
    }


    get updatedByControl(): FormControl {
        return this.postEditorForm?.get('updatedBy') as FormControl;
    }


    get createdDateControl(): FormControl {
        return this.postEditorForm?.get('createdDate') as FormControl;
    }


    get updatedDateControl(): FormControl {
        return this.postEditorForm?.get('updatedDate') as FormControl;
    }


    get contentControl(): FormControl {
        return this.postEditorForm?.get('content') as FormControl;
    }


    get imagesControl(): FormArray {
        return this.postEditorForm?.get('images') as FormArray;
    }


    deleteFromSelectedImages(index: number) {
        this.imagesControl.removeAt(index);
    }
    
    imagesSelectFiles(event: any): void {
        this.imagesSelectedFiles = event.target.files;
        if (this.imagesSelectedFiles && this.imagesSelectedFiles[0]) {
            const numberOfFiles = this.imagesSelectedFiles.length;
            for (let i = 0; i < numberOfFiles; i++) {
                this.imagesControl.push(this.formBuilder.control(this.imagesSelectedFiles[i]));
            }
        }
    }

}