// Generated by andromda-angular cartridge (usecase\use-case-routing.module.ts.vsl) DO NOT EDIT
import { importProvidersFrom } from '@angular/core';
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

import { Shell } from '@app/shell/shell.service';
import { CropsComponent } from '@app/view//crop/crops.component';
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { cropFeature } from '@app/store/crop/crop.reducers';
import { CropEffects } from '@app/store/crop/crop.effects';

import { AuthenticationGuard } from '@app/auth';

import { EditCropImplComponent } from '@app/view/crop/edit-crop-impl.component';
import { SearchCropsImplComponent } from '@app/view/crop/search-crops-impl.component';
import { EditVarietyImplComponent } from '@app/view/crop/edit-variety-impl.component';
import { CropViewImplComponent } from '@app/view/crop/crop-view-impl.component';
import { EditIssueImplComponent } from '@app/view/crop/edit-issue-impl.component';
import { CropControllerImpl } from '@app/controller/crop/crop-controller.impl';
import { Routes } from '@angular/router';

export const routes: Routes = [
  {
    path: '',
    component: CropsComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Crops') },
    providers: [
      CropControllerImpl,
      importProvidersFrom(StoreModule.forFeature(cropFeature)),
      importProvidersFrom(EffectsModule.forFeature([CropEffects])),
    ],
  },
  {
    path: 'edit-crop',
    component: EditCropImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Edit Crop') },
    providers: [
      // []
      CropControllerImpl,
      importProvidersFrom(StoreModule.forFeature(cropFeature)),
      importProvidersFrom(EffectsModule.forFeature([CropEffects])),
    ],
  },
  {
    path: 'search-crops',
    component: SearchCropsImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Search Crops') },
    providers: [
      // []
      CropControllerImpl,
      importProvidersFrom(StoreModule.forFeature(cropFeature)),
      importProvidersFrom(EffectsModule.forFeature([CropEffects])),
    ],
  },
  {
    path: 'edit-variety',
    component: EditVarietyImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Edit Variety') },
    providers: [
      // []
      CropControllerImpl,
      importProvidersFrom(StoreModule.forFeature(cropFeature)),
      importProvidersFrom(EffectsModule.forFeature([CropEffects])),
    ],
  },
  {
    path: 'crop-view',
    component: CropViewImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Crop View') },
    providers: [
      // []
      CropControllerImpl,
      importProvidersFrom(StoreModule.forFeature(cropFeature)),
      importProvidersFrom(EffectsModule.forFeature([CropEffects])),
    ],
  },
  {
    path: 'edit-issue',
    component: EditIssueImplComponent,
    canActivate: [AuthenticationGuard],
    data: { title: marker('Edit Issue') },
    providers: [
      // []
      CropControllerImpl,
      importProvidersFrom(StoreModule.forFeature(cropFeature)),
      importProvidersFrom(EffectsModule.forFeature([CropEffects])),
    ],
  },
];
