// Generated by andromda-jsf cartridge (view\table\table-impl.component.ts.vsl)
import { Component } from '@angular/core';
import { SearchCropsCropsComponent } from '@app/view/crop/search-crops-crops.component';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';

@Component({
  selector: 'app-search-crops-crops',
  templateUrl: './search-crops-crops.component.html',
  styleUrls: ['./search-crops-crops.component.scss'],
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule, TranslateModule, SharedModule, MaterialModule, CsvModule],
})
export class SearchCropsCropsImplComponent extends SearchCropsCropsComponent {
  constructor() {
    super();
  }

  override doSearchCropsEdit(form: any): any {
    return form;
  }

  override doSearchCropsDetails(form: any): any {
    return form;
  }
}
